spring:
  application:
    name: iDashboard-jira-collector
  data:
    mongodb:
      uri: mongodb://idashboard:${spring.data.mongodb.credents}@10.120.100.231/idashboard
      credents: ENC(rwQEK1M5vbHwwhhqx6pBDHn4Ut4IrKHbBUsrB0AUR8XHc8GN/Sf4IRVma96OWroe)

logging:
  level:
    com.cognizant.collector.jira.client.JiraClient: OFF

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

scheduler:
  cron: 0 0/1 * * * *
  enable: true

jiraServer:
  url: "http://10.120.100.231:9090/rest/api/latest"
  username: "Subbu"
  password: "Passw0rd"

server :
  port: 8088

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: LeapSecurityKey
    bean: JasyptEncryptorBean
